In [2]:
import numpy as np

array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

sum = array1+array2
print(sum)

[ 7  9 11 13 15]


In [3]:
sub = array1 - array2

print(sub)


[-5 -5 -5 -5 -5]


In [4]:
mul = array1*array2
print(mul)

[ 6 14 24 36 50]


In [5]:
div = array1/array2
print(div)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [6]:
mean = np.mean(array1)
print(mean)

3.0


In [8]:
sum = np.sum(array1)
print(sum)

15


In [9]:
max = np.max(array1)
min = np.min(array1)

print(min)
print(max)

1
5


In [10]:
greater_than = array1 >3

print(greater_than)

[False False False  True  True]


In [11]:
result = array1 +5
print(result)

[ 6  7  8  9 10]
