In [1]:
import numpy as np

nums = [1,2,3,4,5]

arrayy1 = np.array(nums)
print(arrayy1)

[1 2 3 4 5]


In [2]:
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [3]:
one_array = np.ones(3)
print(one_array)

[1. 1. 1.]


In [5]:
range_array = np.arange(1,10,2)
print(range_array)

[1 3 5 7 9]


In [6]:
random_array = np.random.randint(1,100,5)
print(random_array)

[45 46 32  6  8]


In [7]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.8238973  0.33156943 0.33737945]
 [0.04392795 0.63867738 0.87409243]
 [0.47270233 0.26310235 0.35714722]]


In [8]:
shape = range_array.shape
print(shape)

(5,)


In [9]:
size = range_array.size
print(size)

5


In [10]:
dtype = range_array.dtype
print(dtype)

int64


In [11]:
print(range_array.ndim)

1
