In [1]:
import numpy as np

array1 = np.array([10,20,30,40,50])

secondelment = array1[1]

print(secondelment)


20


In [2]:
print(array1[-2])

40


In [3]:
sliced_arr = array1[1:4]

print(sliced_arr)

[20 30 40]


In [4]:
step_arry = array1[::2]
print(step_arry)

[10 30 50]


In [5]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = matrix[1,1]
print(element)

5


In [6]:
second_row = matrix[1,:]
print(second_row)

[4 5 6]


In [7]:
second_col = matrix[:,1]
print(second_col)

[2 5 8]


In [9]:
data = np.array([1,2,3, np.nan, 4,5])

missing = np.isnan(data)
print(missing)

[False False False  True False False]


In [10]:
data_fill = np.nan_to_num(data, nan =100)
print(data_fill)

[  1.   2.   3. 100.   4.   5.]
